name: Validation Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: nuget/setup-nuget@v1

    - name: Build packages
      run: nuget pack *.nuspec -Version 0.0.0-validationBuild